{
  "comments": [
    {
      "key": {
        "uuid": "eb0ee0d8_50d81485",
        "filename": "catalog-be/src/main/resources/scripts/sdcBePy/tosca/data/beConfig.json",
        "patchSetId": 6
      },
      "lineNbr": 7,
      "author": {
        "id": 5269
      },
      "writtenOn": "2021-08-26T00:15:24Z",
      "side": 1,
      "message": "is there a reason to increase to retry attempts?",
      "range": {
        "startLine": 7,
        "startChar": 18,
        "endLine": 7,
        "endChar": 20
      },
      "revId": "a730774d0e5841df7930f5eaba3f3ca9c33a91dd",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "e8cd1779_c60d77a3",
        "filename": "catalog-be/src/main/resources/scripts/sdcBePy/tosca/data/beConfig.json",
        "patchSetId": 6
      },
      "lineNbr": 7,
      "author": {
        "id": 7592
      },
      "writtenOn": "2021-08-26T01:00:40Z",
      "side": 1,
      "message": "Sometimes init job is failing locally due to 10 failed attempts across all node types, didn\u0027t have this issue at 15.",
      "parentUuid": "eb0ee0d8_50d81485",
      "range": {
        "startLine": 7,
        "startChar": 18,
        "endLine": 7,
        "endChar": 20
      },
      "revId": "a730774d0e5841df7930f5eaba3f3ca9c33a91dd",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": true
    }
  ]
}